kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: {{ .Chart.Name }}-html
            defaultMode: 420
      containers:
        - resources: {}
          volumeMounts:
            - name: index-html
              mountPath: {{ .values.volume.mount.path }}
          terminationMessagePath: /dev/termination-log
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
          readinessProbe:
            httpGet:
              path: {{ .values.probes.readiness.path}} # this check the application url path
              port: {{ .Values.containers.containerPort  }} # In which port the Application is listening
              scheme: HTTP
            initialDelaySeconds: {{ .values.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .values.probes.readiness.periodSeconds }}
            successThreshold: {{ .values.probes.readiness.successThreshold }}
            failureThreshold: {{ .values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .values.probes.liveness.path}}
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .values.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .values.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .values.probes.liveness.periodSeconds }}
            successThreshold: {{ .values.probes.liveness.successThreshold }}
            failureThreshold: {{ .values.probes.liveness.failureThreshold }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10